apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  progressDeadlineSeconds: 1200
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: spmani99/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_ANALYTICS_API
          value: "/api/analytics"
        - name: REACT_APP_GAME_API
          value: "/api/games"
        - name: REACT_APP_ORDER_API
          value: "/api/orders"
        - name: REACT_APP_ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: admin_api_key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"


---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
