apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: spmani99/game-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: game-db-secret
                  key: root_username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: game-db-secret
                  key: root_password
            - name: DB_HOST
              value: "lugx-games-mysql.ca1uo2uoa8cu.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "game_service_db"
            - name: API_KEY
              value: "lgx_admin_z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4"
            - name: PORT
              value: "3001"

---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: ClusterIP
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
