apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
type: Opaque
data:
  clickhouse_url: aHR0cDovL215LWh5cGVyZHgtaGR4LW9zcy12Mi1jbGlja2hvdXNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6ODEyMw==
  clickhouse_user: ZGVmYXVsdA==  
  clickhouse_password: ""
  
  aws_region: dXMtZWFzdC0x
  aws_access_key_id: QUtJQVpRNEQ1RlZUQkVKVUxPN0g=
  aws_secret_access_key: aTh1bkNxM0hRZDlDZTA2QUwvQ3NaNzE1UWpROTErTDc0VmhpSTY3Qw==
  s3_bucket_name: bHVneC1hbmFseXRpY3MtZGVtbw==