apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics-service
          image: spmani99/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: DEBUG_ANALYTICS
              value: "true"
            - name: CLICKHOUSE_URL
              value: "http://localhost:8123"
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD_SECRET
              value: "password"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              value: "dummy"
            - name: AWS_SECRET_ACCESS_KEY
              value: "dummy"
            - name: S3_BUCKET_NAME
              value: "dummy-bucket"
            - name: PORT
              value: "3003"
            - name: UPLOAD_INTERVAL_MINUTES
              value: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003