apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: spmani99/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "lugx-mysql-db.c0toi2wc0ylu.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "order_service_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orderdb-secret
                  key: root_username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: orderdb-secret
                  key: root_password
            - name: API_KEY
              value: "lgx_admin_z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4"
            - name: PORT
              value: "3002"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002